spring:
  datasource:
    url: jdbc:postgresql://main_db:5432/service01
    username: postgres
    password: teach1postgres
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: com.studentProject.entities
      bootstrap-servers: kafka:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer