version: '3.1'

services:

  main_db:
    image: postgres:alpine3.14
    container_name: main_db
    restart: always
    environment:
      POSTGRES_PASSWORD: teach1postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: service01

  main_service:
    build:
      context: StudentProject
    container_name: main_service
    ports:
      - 8080:8080

  backup_service:
    build:
      context: backupService
    container_name: backup_service

  backup_db:
    image: postgres:alpine3.14
    container_name: backup_db
    restart: always
    environment:
      POSTGRES_PASSWORD: teach1postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: service02


  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 22181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1